version: '3.8'

services:
  db:
    image: mysql/mysql-server
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_TCP_PORT: 3308
    ports:
      - "3308:3308"
    volumes:
      - /Users/user/UET/db/int2211/database/init:/docker-entrypoint-initdb.d/:ro
      - /Users/user/UET/db/int2211/database/data:/var/lib/mysql
